"""
Django settings for LeaveApp project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'tua+_)!mo5dn(&7e6rfk)hg)^*p-b-t$d@q-)+(eu8cil9(@i@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'leave',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LeaveApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LeaveApp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-gb'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

EMPLOYEE_FTE_DEFAULT_HOURS = 8
EMPLOYEE_FTE_DEFAULT_HOURS_WEEK = 40
EMPLOYEE_FTE_DEFAULT_TR_COUNT = 18

EMPLOYEE_FTE_LEAVE_HOURS = 240 # leave hours for a full time employee

LEAVE_TYPES_CHOICES = (
    (0, 'Leave Apply'),
    (1, 'Sickness Leave'),
    (2, 'Special Leave'),
    (3, 'Political Leave'),
)

LEAVE_PERIODIC_CHOICES = (
    (0,'once'),
    (1,'weekly'),
    (2,'bi-weekly'),
    (3,'monthly'),
    (4,'trimestrial'),
    (5,'semestrial'),
    (6,'yearly'),
)

# EMPLOYEE_DEFAULT_DAY = [starttime,lunchtime,lunchlength(mins),endtime]
EMPLOYEE_DEFAULT_DAY = ['08:00','12:00',60,'17:00']
EMPLOYEE_DEFAULT_SCHEDULE = {
    'monday': EMPLOYEE_DEFAULT_DAY,
    'tuesday': EMPLOYEE_DEFAULT_DAY,
    'wednesday': EMPLOYEE_DEFAULT_DAY,
    'thursday': EMPLOYEE_DEFAULT_DAY,
    'friday' : EMPLOYEE_DEFAULT_DAY,
    'saturday': [],
    'sunday': [],
}

# Leave can be taken until march 31st of the next year
EMPLOYEE_LEAVE_NEXT_YEAR_LIMIT = [31,3,1]
EMPLOYEE_MAX_LEAVE_TO_NEXT_YEAR = EMPLOYEE_FTE_DEFAULT_HOURS*10 # 10 days in hours

EMPLOYEE_SPECIAL_LEAVE_DAYS = {
    'marriage': 16,
    'child-birth': 48,
    'address-change': 16,
    'death-close': 16,
    'death-relative': 8,
}

# recover on [monday, tuesday, wednesday, thursday, friday, saturday, sunday]
EMPLOYEE_PUBLIC_HOLIDAY_RECOVER = [0,0,0,0,0,1,1]

MIN_PASSWORD_LENGTH = 12

ADMIN_LIST = ['theadmin@mail.com',]